### ISSUE TITLE
Plugin does not work in 0.4.0

### ISSUE THREAD

**Issue by jpnkicker14** [pencilblue/dropbox-pencilblue#4]
After updating the media provider in the config.js and installing the plugin, the MediaService errors when going to any page that deals with the MediaService.

**Comment by brianhyder** [comment]
Hey, sorry for the delay.  I'll be looking into this today.  Are there any stack traces you are willing to pass along?

**Comment by brianhyder** [comment]
I am unable to reproduce the issue.

Did you update the settings for plugin?

**Comment by jpnkicker14** [comment]
I just pulled the latest pencilblue code and it seemed to resolve this issue.  Thanks
