### ISSUE TITLE
Installing dropbox-pencilblue

### ISSUE THREAD

**Issue by t0t** [pencilblue/dropbox-pencilblue#5]
hi!,

excuse me for this dummy question but...
Is not dangerous expose your Dropbox credentials in a json file? I supouse that Node hides it. 
Can you explain a bit?

Thanks.
https://github.com/pencilblue/dropbox-pencilblue/blob/master/details.json#L18-L36

**Comment by brianhyder** [comment]
Sorry for the late response.  The credentials are not modified in the details.json file.  They are actually stored in the DB.  The fields in the details.json file just become the properties that the plugin needs along with default values.
