### ISSUE TITLE
Error (Failed to load & parse the details.json file.) - Heroku

### ISSUE THREAD

**Issue by jensanity5000** [pencilblue/dropbox-pencilblue#8]
Using Heroku, I get the following on the last step when trying to click install from /admin/plugins then add  dropbox details:

Failed to load & parse the details.json file.
An invalid details file was provided for plugin. Error: ENOENT: no such file or directory, open '/app/plugins/dropbox-pencilblue/details.json' at Error (native)

The files have been cloned and the details file is present where it should be like all other example plugins.

Any ideas?

**Comment by brianhyder** [comment]
Does the plugin UID in the details.json file for Dropbox match the
directory name where Dropbox is cloned on heroku?

**Comment by jensanity5000** [comment]
Hi @brianhyder,

yes it does match.

**Comment by brianhyder** [comment]
Can you confirm PB version?

That's weird.  The ```ENOENT``` means "Error, No Entity".  It can't find the details.json file.  If you remote into the instance can you see the file in that path?  

In your configuration, can you set ```cluster.self_managed=false```?  I'm wondering if the spin off of a process is affecting the read permissions.  Disabling the self managed cluster only 1 process will spin off.

**Comment by jensanity5000** [comment]
Ahhh so when I remote into heroku the folder is there for the plugin but no files are in it, however they are there locally.

**Comment by jensanity5000** [comment]
@brianhyder, thanks for your help so far...

So not sure what happened but I manually recreated the folder with a new name and pasted files in and lined up the folder name in details.json.  Now I get the plugin listed and the button to install.

However seems frozen at this step during install in the admin ui:
Inspecting plugin on disk at: /app/plugins/dropbox-media-storage/details.json

How long should it take? anything wrong with the above approach?

**Comment by jensanity5000** [comment]
Refreshing page and clicking install again and it now installs fully.  I am then able to add and saving the dropbox tokens and keys.
